# Generated by Django 6.0.5 on 2026-05-11 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Car",
        ),
    ]
