# Generated by Django 6.0.5 on 2026-05-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_aboutus_banner_category_product_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
