# Generated by Django 6.0.5 on 2026-05-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_order_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutus",
            name="address_url",
            field=models.TextField(default="https://www.google.com/maps"),
        ),
    ]
