# Generated by Django 6.0.5 on 2026-05-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_aboutus_address_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutus",
            name="address_url",
            field=models.TextField(null=True),
        ),
    ]
